### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by twotired** [fgouteroux/terraform-provider-mimir#2] opened 2022-11-22 22:09 UTC
This is on OS X and happens frequently:
```
 The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-mimir_v0.0.5 plugin:

fatal error: concurrent map iteration and map write

goroutine 85 [running]:
runtime.throw({0x19d61d9, 0x150})
	runtime/panic.go:1198 +0x71 fp=0xc0007b3060 sp=0xc0007b3030 pc=0x10355f1
runtime.mapiternext(0x1947240)
	runtime/map.go:858 +0x4eb fp=0xc0007b30d0 sp=0xc0007b3060 pc=0x100f7cb
github.com/fgouteroux/terraform-provider-mimir/mimir.(*api_client).send_request(0xc0000fe600, {0x19b1d36, 0x2}, {0x19b0396, 0x3}, {0xc0002f0d80, 0x19bcfa6}, {0x0, 0x11}, 0x0)
	github.com/fgouteroux/terraform-provider-mimir/mimir/api_client.go:160 +0x356 fp=0xc0007b32b0 sp=0xc0007b30d0 pc=0x1805196
github.com/fgouteroux/terraform-provider-mimir/mimir.ruleAlertingRead({0x108dcca, 0x1c58480}, 0xc000138e00, {0x18bbde0, 0xc0000fe600})
	github.com/fgouteroux/terraform-provider-mimir/mimir/resource_mimir_rule_group_alerting.go:167 +0x22b fp=0xc0007b33a8 sp=0xc0007b32b0 pc=0x180b6cb
github.com/fgouteroux/terraform-provider-mimir/mimir.resourcemimirRuleGroupAlertingRead({0x1c58448, 0xc0002d1380}, 0x2459a68, {0x18bbde0, 0xc0000fe600})
	github.com/fgouteroux/terraform-provider-mimir/mimir/resource_mimir_rule_group_alerting.go:106 +0x31 fp=0xc0007b33f0 sp=0xc0007b33a8 pc=0x180a971
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000300ee0, {0x1c58480, 0xc0007ceed0}, 0xd, {0x18bbde0, 0xc0000fe600})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:724 +0x12e fp=0xc0007b3468 sp=0xc0007b33f0 pc=0x163e22e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000300ee0, {0x1c58480, 0xc0007ceed0}, 0xc000812a90, {0x18bbde0, 0xc0000fe600})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:1015 +0x585 fp=0xc0007b3680 sp=0xc0007b3468 pc=0x1640545
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c078, {0x1c583d8, 0xc000598800}, 0xc0000a8000)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:613 +0x574 fp=0xc0007b37a0 sp=0xc0007b3680 pc=0x1635034
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003dd7c0, {0x1c58480, 0xc0007e21b0}, 0xc000a04180)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:746 +0x48c fp=0xc0007b3b48 sp=0xc0007b37a0 pc=0x1507fcc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1982620, 0xc0003dd7c0}, {0x1c58480, 0xc0007e21b0}, 0xc0006c6000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170 fp=0xc0007b3ba0 sp=0xc0007b3b48 pc=0x14f1930
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00024f6c0, {0x1c66dc0, 0xc000502340}, 0xc000884240, 0xc000239080, 0x222fc70, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb03 fp=0xc0007b3e48 sp=0xc0007b3ba0 pc=0x1460ec3
google.golang.org/grpc.(*Server).handleStream(0xc00024f6c0, {0x1c66dc0, 0xc000502340}, 0xc000884240, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2a fp=0xc0007b3f68 sp=0xc0007b3e48 pc=0x1464fea
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98 fp=0xc0007b3fe0 sp=0xc0007b3f68 pc=0x145eb38
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0007b3fe8 sp=0xc0007b3fe0 pc=0x10667e1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x294

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc00005a180)
	github.com/hashicorp/go-plugin@v1.4.3/server.go:469 +0x1473
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0x19b5279, 0xa413c20}, 0xc0003a51e0, {0x0, 0x0, 0x0})
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:311 +0xbaa
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf5serverServe(0xc00005a120)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/plugin/serve.go:178 +0x518
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc00005a120)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/plugin/serve.go:118 +0x177
main.main()
	github.com/fgouteroux/terraform-provider-mimir/main.go:21 +0xda

goroutine 10 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x0)
	github.com/hashicorp/go-plugin@v1.4.3/grpc_broker.go:121 +0x6d
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc000108780)
	github.com/hashicorp/go-plugin@v1.4.3/grpc_broker.go:411 +0x48
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
	github.com/hashicorp/go-plugin@v1.4.3/grpc_server.go:85 +0x469

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0xa618fd0, 0x72)
	runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc00005a720, 0xc000055000, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00005a720, {0xc000055000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:32
os.(*File).Read(0xc0000a6158, {0xc000055000, 0x400, 0x18987a0})
	os/file.go:119 +0x5e
bufio.(*Reader).Read(0xc0002a4f40, {0xc0000f6400, 0x400, 0x0})
	bufio/bufio.go:227 +0x1b4
github.com/hashicorp/go-plugin.copyChan({0x1c71b30, 0xc0001ad3b0}, 0x0, {0x1c44fe0, 0xc0000a6158})
	github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:181 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:37 +0xfa

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0xa618df0, 0x72)
	runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc00005a7e0, 0xc0003e5000, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00005a7e0, {0xc0003e5000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:32
os.(*File).Read(0xc0000a6178, {0xc0003e5000, 0x400, 0x18987a0})
	os/file.go:119 +0x5e
bufio.(*Reader).Read(0xc0002a5740, {0xc0000f6800, 0x400, 0x0})
	bufio/bufio.go:227 +0x1b4
github.com/hashicorp/go-plugin.copyChan({0x1c71b30, 0xc0001ad3b0}, 0x0, {0x1c44fe0, 0xc0000a6178})
	github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:181 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.3/grpc_stdio.go:38 +0x188

goroutine 14 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:166 +0x28
os/signal.loop()
	os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2c

Error: The terraform-provider-mimir_v0.0.5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by fgouteroux** [comment] 2022-11-24 08:48
Hi @twotired 

Could you give more context please ? Provider config, resource... It could be useful to reproduce the issue. Thanks

**Comment by fgouteroux** [comment] 2022-11-24 14:58
@twotired Did you configure the mimir provider with a token ?

In the crash logs:
```
github.com/fgouteroux/terraform-provider-mimir/mimir.(*api_client).send_request(0xc0000fe600, {0x19b1d36, 0x2}, {0x19b0396, 0x3}, {0xc0002f0d80, 0x19bcfa6}, {0x0, 0x11}, 0x0)
	github.com/fgouteroux/terraform-provider-mimir/mimir/api_client.go:160 
```
 it refer to this code https://github.com/fgouteroux/terraform-provider-mimir/blob/d2de9386633cc376cca00b722257a3a765ffc85d/mimir/api_client.go#L158-L163

I think that the error message `fatal error: concurrent map iteration and map write` is caused by this code https://github.com/fgouteroux/terraform-provider-mimir/blob/6e9e2f69d4e8dbb07078b67b9f4fc516283ceb8d/mimir/api_client.go#L154-L156

Setting the header in the client object should not happen as we could have concurrent threads writing in the map while others are reading. 
The Authorization header should be set in the request and not in the client. 

Fixed in https://github.com/fgouteroux/terraform-provider-mimir/commit/d2de9386633cc376cca00b722257a3a765ffc85d

This release should be fix this [issue](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v0.0.6)

**Comment by twotired** [comment] 2022-11-24 16:43
Thanks. Will test it next week.

**Comment by fgouteroux** [comment] 2022-12-14 16:45
@twotired did you try the latest release ?

**Comment by twotired** [comment] 2022-12-15 06:18
It's working well, thanks!

**Closed** 2022-12-15 06:57 UTC
